"""init

Revision ID: 4b0eef5caa6e
Revises: fbad4d5ce3e1
Create Date: 2026-03-24 18:51:03.766459

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b0eef5caa6e'
down_revision: Union[str, Sequence[str], None] = 'fbad4d5ce3e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=False),
    sa.Column('marka', sa.String(length=100), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('color', sa.String(length=100), nullable=True),
    sa.Column('engine', sa.String(length=100), nullable=False),
    sa.Column('drive', sa.String(length=20), nullable=False),
    sa.Column('fuel', sa.String(length=50), nullable=False),
    sa.Column('mileage', sa.String(length=50), nullable=False),
    sa.Column('year', sa.String(length=50), nullable=False),
    sa.Column('budget', sa.String(length=100), nullable=False),
    sa.Column('repairs', sa.String(length=250), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('leads')
    # ### end Alembic commands ###
