"""init

Revision ID: 55d84489a518
Revises: 8d6f0c5e2d43
Create Date: 2026-03-25 14:19:49.564992

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '55d84489a518'
down_revision: Union[str, Sequence[str], None] = '8d6f0c5e2d43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('leads', 'phone',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('leads', 'marka',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('leads', 'model',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('leads', 'engine',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('leads', 'drive',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('leads', 'fuel',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('leads', 'mileage',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('leads', 'year',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('leads', 'budget',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('leads', 'repairs',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
    op.alter_column('leads', 'url',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
    op.alter_column('leads', 'image_data',
               existing_type=postgresql.BYTEA(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('leads', 'image_data',
               existing_type=postgresql.BYTEA(),
               nullable=False)
    op.alter_column('leads', 'url',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
    op.alter_column('leads', 'repairs',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
    op.alter_column('leads', 'budget',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('leads', 'year',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('leads', 'mileage',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('leads', 'fuel',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('leads', 'drive',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('leads', 'engine',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('leads', 'model',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('leads', 'marka',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('leads', 'phone',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    # ### end Alembic commands ###
