"""init

Revision ID: 845f15eac26e
Revises: 4b0eef5caa6e
Create Date: 2026-03-24 19:50:39.291065

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '845f15eac26e'
down_revision: Union[str, Sequence[str], None] = '4b0eef5caa6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leads', sa.Column('url', sa.String(length=250), nullable=False))
    op.add_column('leads', sa.Column('image_data', sa.LargeBinary(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leads', 'image_data')
    op.drop_column('leads', 'url')
    # ### end Alembic commands ###
